name: GitHub 3D Contribution Calendar

on:
  schedule:
    - cron: "0 18 * * *"   # todos los días a medianoche UTC-6
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution Graph

    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: |
            {
              "githubUserName": "al3w0f205",
              "fileName": "profile-3d-contrib/profile-night-rainbow.svg",
              "startForeColor": [0, 0, 0, 0],
              "endForeColor": [88, 166, 255, 255],
              "startBackColor": [0, 13, 33, 255],
              "endBackColor": [0, 13, 33, 255],
              "dotColor": [88, 166, 255, 128],
              "calendarPadding": 2,
              "startDate": null,
              "contributionTypes": [
                "commitContributionsByRepository",
                "pullRequestContributionsByRepository",
                "pullRequestReviewContributionsByRepository",
                "issueContributionsByRepository",
                "repositoryContributions"
              ]
            }

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
